// src/data/hospitalData.js
import AIIMSimg from "../../../assets/aiims.jpeg"
import Maximg from "../../../assets/Max.jpg"
import Hemeimg from "../../../assets/Heme.jpg"

const hospitalData = [
    {
      _id: 1,
      name: 'AIIMs Hospital',
      bed: 100,
      totalbed: 120,
      embed: 10,
      emtotalbed: 12,
      discription: 'Description A',
      Special: 'Heart speacial/ General / Emergency',
      location:'Greater Noida, Up-211310',
      image: AIIMSimg,
    },
    {
      _id: 2,
      name: 'MAX Hospital',
      bed: 200,
      totalbed: 400,
      embed: 10,
      emtotalbed: 12,
      discription: 'Description B',
      Special: 'Heart speacial/ General / Emergency',
      location:'Noida, Up-201910',
      image: Maximg,
    },
    {
      _id: 3,
      name: 'HEmergency Hospital',
      bed: 300,
      totalbed: 400,
      embed: 10,
      emtotalbed: 12,
      discription: 'Description C',
      Special: 'Heart speacial/ General / Emergency',
      location:'Delhi, Delhi-100010',
      image: Hemeimg,
    },
    {
        _id: 4,
        name: 'Fortis Healthcare',
        bed: 100,
        totalbed: 120,
        embed: 10,
        emtotalbed: 12,
        discription: 'Description A',
        Special: 'Heart speacial/ General / Emergency',
        location:'Greater Noida, Up-211310',
        image: AIIMSimg,
      },
      {
        _id: 5,
        name: "Apollo Hospitals",
        bed: 200,
        totalbed: 400,
        embed: 10,
        emtotalbed: 12,
        discription: 'Description B',
        Special: 'Heart speacial/ General / Emergency',
        location:'Noida, Up-201910',
        image: Maximg,
      },
      {
        _id: 6,
        name: "Manipal Hospitals",
        bed: 300,
        totalbed: 400,
        embed: 10,
        emtotalbed: 12,
        discription: 'Description C',
        Special: 'Heart speacial/ General / Emergency',
        location:'Delhi, Delhi-100010',
        image: Hemeimg,
      },
      {
        _id: 6,
        name: "Manipal Hospitals",
        bed: 300,
        totalbed: 400,
        embed: 10,
        emtotalbed: 12,
        discription: 'Description C',
        Special: 'Heart speacial/ General / Emergency',
        location:'Delhi, Delhi-100010',
        image: Hemeimg,
      },
      {
        id: 7,
          name: "Lilavati Hospital",
        bed: 300,
        totalbed: 400,
        embed: 7,
        emtotalbed: 15,
        discription: 'Description C',
        Special: 'Heart speacial/ General / Emergency',
        location:'Delhi, Delhi-100010',
        image: Hemeimg,
      },
      {
        id: 8,
          name: "Columbia Asia",
        bed: 300,
        totalbed: 400,
        embed: 20,
        emtotalbed: 50,
        discription: 'Description C',
        Special: 'Nurolofy/ General / Emergency',
        location:'Delhi, Delhi-100010',
        image: Hemeimg,
      },
      {
        id: 9,
          name: "Kokilaben Dhirubhai Ambani Hospital",
        bed: 300,
        totalbed: 400,
        embed: 0,
        emtotalbed: 0,
        discription: 'Description C',
        Special: 'orthopedic/ General',
        location:'Delhi, Delhi-100010',
        image: Hemeimg,
      },
      {
        id: 10,
          name: "Jaslok Hospital",
        bed: 300,
        totalbed: 400,
        embed: 0,
        emtotalbed: 0,
        discription: 'Description C',
        Special: 'Heart speacial/ General',
        location:'Delhi, Delhi-100010',
        image: Hemeimg,
      },
    // Add more items as needed
  ];
  
  export default hospitalData;
  